test: Add test spreadsheets
USSF-ORBIT/ussf-personnel-api pull request #6
Opened 2023-08-22 15:20 UTC by jcbcapps

# SC-2186

## Proposed changes
- Add spreadsheets with test data using the mock users we have in the `users.php` file in the ussf-portal-client repo

---

## Reviewer notes

---

## Setup

---

2023-08-23 18:54 UTC, abbyoung commented
Data looks good! Q for you and @gidjin: Do we want to include instructions or some code that allows for easier switching between s3 data and this data? Or how are we envisioning this working? Maybe that's a different PR..

2023-08-23 19:05 UTC, jcbcapps commented
> Data looks good! Q for you and @gidjin: Do we want to include instructions or some code that allows for easier switching between s3 data and this data? Or how are we envisioning this working? Maybe that's a different PR..

@abbyoung good question. I'm not sure. I was thinking we could just look at an `.env` variable or something. Seems like a good discussion for eng sync?

2023-08-23 21:12 UTC, gidjin commented
> > Data looks good! Q for you and @gidjin: Do we want to include instructions or some code that allows for easier switching between s3 data and this data? Or how are we envisioning this working? Maybe that's a different PR..
> 
> @abbyoung good question. I'm not sure. I was thinking we could just look at an `.env` variable or something. Seems like a good discussion for eng sync?

In the CMS we look at the bucket name to switch between local vs S3. Probably could do the same here and have `.envrc` contain the default name to use local and `.envrc.local` can be added to switch to S3 if needed.

2023-08-23 21:13 UTC, gidjin commented
@abbyoung & @jcbcapps I went and looked and that's what decides between s3 and local now see https://github.com/USSF-ORBIT/ussf-personnel-api/blob/a362e690e953420fb7cff518aa443ecafa297fe8/src/helpers.ts#L15

2023-08-23 21:28 UTC, gidjin requested changes
Suggestion: I think the sample files should be named the same as what we expect them to be in S3. 

See: `src/constants.ts`
```typescript
export const officerFilename = 'officer_personnel_data.xlsx'
export const enlistedFilename = 'enlisted_personnel_data.xlsx'
```

2023-08-24 22:19 UTC, gidjin approved these changes

2023-08-24 22:19 UTC, gidjin commented on src/resolvers.ts
> +import { enlistedUserColumns, officerUserColumns } from "./constants.js";
Thought: This is why I'd like to apply our eslint rules, for consistency. But not part of this pr.

2023-08-24 22:19 UTC, gidjin commented on src/resolvers.ts
> +        return value?.toString().trim();
Thought: I wonder if we should trim the input id too. I'm less worried because that's coming from apis and us but it crossed my mind.

2023-08-24 22:19 UTC, gidjin commented on src/resolvers.ts
> +      const foundUser = worksheet.getRow(foundUserRow);
praise: Nice improvement, the below is much easier to read now.

2023-08-29 18:48 UTC, merged